[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://huhowbvebjhafbqhiaci.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_hcdVSHbJZ0EErhrg_n1wBA_Jvfdeyrc"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
